---
- name: Install Docker and Docker Compose
  hosts: all
  gather_facts: true
  become: yes

  tasks:
    - name: Add Google DNS to resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 8.8.8.8"
        insertafter: "^#nameserver"
    
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"

    
    - name: Add Docker APT GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Update apt cache (again after adding repo)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install Docker Compose
      shell: curl -sSL https://github.com/docker/compose/releases/download/$(curl -sSL https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d '"' -f 4)/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      args:
        executable: /bin/bash
  vars:
    ansible_become_pass: ****
